genieacs-gui/config/routes.rb
# Need to not fail when uri contains curly braces
# This overrides the DEFAULT_PARSER with the UNRESERVED key, including '{' and '}'
# DEFAULT_PARSER is used everywhere, so its better to override it once
module URI
  remove_const :DEFAULT_PARSER
  unreserved = REGEXP::PATTERN::UNRESERVED
  DEFAULT_PARSER = Parser.new(:UNRESERVED => unreserved + "\{\}\^")
end

GenieacsGui::Application.routes.draw do
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'log_in' => 'sessions#create'

  root 'home#index'
  get 'devices' => 'devices#index'
  get 'devices/:id' => 'devices#show'
  post 'devices/:id' => 'devices#update'
  delete 'devices/:id' => 'devices#destroy'

  get 'faults' => 'faults#index'
  delete 'faults/:id' => 'faults#destroy'
  post 'tasks/:id/retry' => 'faults#retry_task'
  delete 'tasks/:id' => 'faults#destroy_task'

  get 'presets' => 'presets#index'
  get 'presets/new' => 'presets#new'
  get 'presets/:id/edit' => 'presets#edit'
  post 'presets' => 'presets#update'
  delete 'presets/:id' => 'presets#destroy'

  get 'objects' => 'objects#index'
  get 'objects/new' => 'objects#new'
  get 'objects/:id/edit' => 'objects#edit'
  post 'objects' => 'objects#update'
  delete 'objects/:id' => 'objects#destroy'

  get 'provisions' => 'provisions#index'
  get 'provisions/new' => 'provisions#new'
  get 'provisions/:id/edit' => 'provisions#edit'
  post 'provisions' => 'provisions#update'
  delete 'provisions/:id' => 'provisions#destroy'

  get 'virtual_parameters' => 'virtual_parameters#index'
  get 'virtual_parameters/new' => 'virtual_parameters#new'
  get 'virtual_parameters/:id/edit' => 'virtual_parameters#edit'
  post 'virtual_parameters' => 'virtual_parameters#update'
  delete 'virtual_parameters/:id' => 'virtual_parameters#destroy'

  get 'files' => 'files#index'
  get 'files/new' => 'files#new'
  post 'files' => 'files#upload'
  delete 'files/:id' => 'files#destroy', :constraints => { :id => /.*/ }

  get 'ping/:ip' => 'ping#index', :constraints => { :ip => /[0-9\.]+|[0-9a-f:]+/ }

  resources :users do
    resources :user_roles
  end
  resources :roles do
    resources :privileges
  end

  if Rails.configuration.auth_method == :db
    get 'change_password' => 'change_password#index'
    post 'change_password' => 'change_password#update'
  end
end

genieacs-gui/app/controllers/files_controller.rb
class FilesController < ApplicationController
  require 'net/http'
  require 'json'
  require 'util'

  # GET /files
  # GET /files.json
  def index
    can?(:read, 'files') do
      skip = params.include?(:page) ? (Integer(params[:page]) - 1) * Rails.configuration.page_size : nil

      res = query_resource(create_api_conn(), 'files', nil, nil, skip, Rails.configuration.page_size)
      @files = res[:result]
      @total = res[:total]

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @files }
      end
    end
  end

  # GET /files/new
  # GET /files/new.json
  def new
    can?(:create, 'files') do
      @file = {}

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @file }
      end
    end
  end

  # POST /files
  def upload
    can?(:create, 'files') do
      http = create_api_conn()
      req = Net::HTTP::Put.new("/files/#{URI.escape(params[:file].original_filename)}")
      req.body = params[:file].read
      req['fileType'] = params[:file_type].strip
      req['oui'] = params[:oui].strip
      req['productClass'] = params[:product_class].strip
      req['version'] = params[:version].strip
      res = http.request(req)

      if res.code == '201'
        flash[:success] = 'File saved'
      else
        flash[:error] = "Unexpected error (#{res.code}): #{res.body}"
      end

      redirect_to :action => :index
    end
  end

  # DELETE /files/1
  # DELETE /files/1.json
  def destroy
    can?(:delete, 'files') do
      filename = params[:id]
      http = create_api_conn()
      res = http.delete("/files/#{URI.escape(filename)}", nil)
      if res.code == '200'
        flash[:success] = 'File deleted'
      else
        flash[:error] = "Unexpected error (#{res.code}): #{res.body}"
      end

      redirect_to :action => :index
    end
  end
end

genieacs-gui/app/views/files/_form.html.erb
<%= form_tag({:action => :upload}, :method => 'post', :multipart => true) do %>
<div>
  <%= label_tag('file_type', 'File type:') %>
  <%= select_tag('file_type', options_for_select(['1 Firmware Upgrade Image', '2 Web Content', '3 Vendor Configuration File', '4 Tone File', '5 Ringer File'], '1 Firmware Upgrade Image')) %>
</div>
<div>
  <%= label_tag('oui', 'OUI:') %>
  <%= text_field_tag 'oui', params[:oui] %>
</div>
<div>
  <%= label_tag('product_class', 'Product class:') %>
  <%= text_field_tag 'product_class', params[:product_class] %>
</div>
<div>
  <%= label_tag('version', 'Version:') %>
  <%= text_field_tag 'version', params[:version] %>
</div>
<div>
  <%= label_tag('file', 'File:') %>
  <%= file_field_tag('file') %>
</div>
<br/>
<%= submit_tag("Upload") %>
<% end %>

genieacs-gui/app/views/files/index.html.erb
<%
content_for :title do 'File List' end
%>
<h1>Listing files</h1>

<h2>Showing <%= @total %> files</h2>

<table class="records">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>OUI</th>
    <th>Product class</th>
    <th>Version</th>
    <th></th>
  </tr>

<% @files.each do |file| %>
  <tr>
    <td><%= file['filename'] %></td>
    <td><%= file['metadata']['fileType'] rescue '' %></td>
    <td><%= file['metadata']['oui'] rescue '' %></td>
    <td><%= file['metadata']['productClass'] rescue '' %></td>
    <td><%= file['metadata']['version'] rescue '' %></td>
    <td class="action"><%= link_to 'Destroy', {controller: 'files', action: 'destroy', id: file['filename']}, method: :delete, data: { confirm: 'Are you sure?' } if can?(:delete, 'files') %></td>
  </tr>
<% end %>
</table>

<%= render partial: 'pagination' %>

<br />

<%= link_to 'New File', {:action => :new} if can?(:create, 'files') %>

genieacs-gui/app/views/files/new.html.erb
<%
content_for :title do 'Add New File' end
%>
<h1>New file</h1>

<%= render 'form' %>

<%= link_to 'Back', files_path %>