genieacs-gui/config/routes.rb
# Need to not fail when uri contains curly braces
# This overrides the DEFAULT_PARSER with the UNRESERVED key, including '{' and '}'
# DEFAULT_PARSER is used everywhere, so its better to override it once
module URI
  remove_const :DEFAULT_PARSER
  unreserved = REGEXP::PATTERN::UNRESERVED
  DEFAULT_PARSER = Parser.new(:UNRESERVED => unreserved + "\{\}\^")
end

GenieacsGui::Application.routes.draw do
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'log_in' => 'sessions#create'

  root 'home#index'
  get 'devices' => 'devices#index'
  get 'devices/:id' => 'devices#show'
  post 'devices/:id' => 'devices#update'
  delete 'devices/:id' => 'devices#destroy'

  get 'faults' => 'faults#index'
  delete 'faults/:id' => 'faults#destroy'
  post 'tasks/:id/retry' => 'faults#retry_task'
  delete 'tasks/:id' => 'faults#destroy_task'

  get 'presets' => 'presets#index'
  get 'presets/new' => 'presets#new'
  get 'presets/:id/edit' => 'presets#edit'
  post 'presets' => 'presets#update'
  delete 'presets/:id' => 'presets#destroy'

  get 'objects' => 'objects#index'
  get 'objects/new' => 'objects#new'
  get 'objects/:id/edit' => 'objects#edit'
  post 'objects' => 'objects#update'
  delete 'objects/:id' => 'objects#destroy'

  get 'provisions' => 'provisions#index'
  get 'provisions/new' => 'provisions#new'
  get 'provisions/:id/edit' => 'provisions#edit'
  post 'provisions' => 'provisions#update'
  delete 'provisions/:id' => 'provisions#destroy'

  get 'virtual_parameters' => 'virtual_parameters#index'
  get 'virtual_parameters/new' => 'virtual_parameters#new'
  get 'virtual_parameters/:id/edit' => 'virtual_parameters#edit'
  post 'virtual_parameters' => 'virtual_parameters#update'
  delete 'virtual_parameters/:id' => 'virtual_parameters#destroy'

  get 'files' => 'files#index'
  get 'files/new' => 'files#new'
  post 'files' => 'files#upload'
  delete 'files/:id' => 'files#destroy', :constraints => { :id => /.*/ }

  get 'ping/:ip' => 'ping#index', :constraints => { :ip => /[0-9\.]+|[0-9a-f:]+/ }

  resources :users do
    resources :user_roles
  end
  resources :roles do
    resources :privileges
  end

  if Rails.configuration.auth_method == :db
    get 'change_password' => 'change_password#index'
    post 'change_password' => 'change_password#update'
  end
end

genieacs-gui/app/controllers/virtual_parameters_controller.rb
class VirtualParametersController < ApplicationController
  require 'net/http'
  require 'json'
  require 'util'

  # GET /virtual_parameters
  # GET /virtual_parameters.json
  def index
    can?(:read, 'virtual_parameters') do
      skip = params.include?(:page) ? (Integer(params[:page]) - 1) * Rails.configuration.page_size : nil

      res = query_resource(create_api_conn(), 'virtual_parameters', nil, nil, skip, Rails.configuration.page_size)
      @virtual_parameters = res[:result]
      @total = res[:total]

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @virtual_parameters }
      end
    end
  end

  # GET /virtual_parameters/new
  # GET /virtual_parameters/new.json
  def new
    can?(:create, 'virtual_parameters') do
      @virtual_parameter = {}

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @virtual_parameter }
      end
    end
  end

  # GET /virtual_parameters/1/edit
  def edit
    can?(:update, 'virtual_parameters') do
      id = params[:id]
      res = query_resource(create_api_conn(), 'virtual_parameters', {'_id' => id})
      @virtual_parameter = res[:result][0] || {}
    end
  end

  # PUT /virtual_parameters/1
  # PUT /virtual_parameters/1.json
  def update
    can?(:update, 'virtual_parameters') do
      script = params['script']

      http = create_api_conn()
      res = http.put("/virtual_parameters/#{URI.escape(params['name'].strip)}", script)
      if res.code == '200'
        flash[:success] = 'Virtual parameter saved'
      else
        flash[:error] = "Unexpected error (#{res.code}): #{res.body}"
      end

      redirect_to :action => :index
    end
  end

  # DELETE /virtual_parameters/1
  # DELETE /virtual_parameters/1.json
  def destroy
    can?(:delete, 'virtual_parameters') do
      http = create_api_conn()
      res = http.delete("/virtual_parameters/#{URI.escape(params[:id])}", nil)
      if res.code == '200'
        flash[:success] = 'Virtual parameter deleted'
      else
        flash[:error] = "Unexpected error (#{res.code}): #{res.body}"
      end

      redirect_to :action => :index
    end
  end
end

genieacs-gui/app/views/virtual_parameters/_form.html.erb
<%= form_tag({:action => :update}) do %>
<div class="field">
  <label for="name">Name</label><br />
  <input id="name" name="name" type="text" <%= 'readonly' if @virtual_parameter.include? '_id' %> value="<%= @virtual_parameter['_id'] %>" />
</div>

<br/>
<div class="field">
  <label for="weight">Script</label><br />
  <textarea id="script" name="script" cols="80" rows="24"><%= h @virtual_parameter['script'] %></textarea>
</div>

<br/>
<div class="actions">
  <input type="submit" value="Save" />
</div>
<% end %>

<script type="text/javascript">
$(function() {
  // Skip if Turbolinks preview
  if (document.documentElement.hasAttribute("data-turbolinks-preview"))
    return;

  CodeMirror.fromTextArea(document.getElementById("script"), {mode: "javascript", lineNumbers: true});
});
</script>

genieacs-gui/app/views/virtual_parameters/edit.html.erb
<%
content_for :title do 'Edit Virtual Parameter ' + @virtual_parameter['_id'] end
%>
<h1>Editing virtual parameter</h1>

<%= render 'form' %>

genieacs-gui/app/views/virtual_parameters/index.html.erb
<%
content_for :title do 'Virtual Parameter List' end
%>
<h1>Listing virtual parameters</h1>

<h2>Showing <%= @total %> virtual parameters</h2>

<table class="records">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @virtual_parameters.each do |virtual_parameter| %>
  <tr>
    <td><%= virtual_parameter['_id'] %></td>
    <td class="action"><%= link_to 'Edit', {:action => :edit, :id => virtual_parameter['_id']} if can?(:update, 'virtual_parameters') %></td>
    <td class="action"><%= link_to 'Destroy', {:action => :destroy, :id => virtual_parameter['_id']}, method: :delete, data: { confirm: 'Are you sure?' } if can?(:delete, 'virtual_parameters') %></td>
  </tr>
<% end %>
</table>

<%= render partial: 'pagination' %>

<br />

<%= link_to 'New virtual parameter', {:action => :new} if can?(:create, 'virtual_parameters') %>

genieacs-gui/app/views/virtual_parameters/new.html.erb
<%
content_for :title do 'New Virtual Parameter' end
%>
<h1>New virtual parameter</h1>

<%= render 'form' %>

<%= link_to 'Back', virtual_parameters_path %>