genieacs-gui/config/routes.rb
# Need to not fail when uri contains curly braces
# This overrides the DEFAULT_PARSER with the UNRESERVED key, including '{' and '}'
# DEFAULT_PARSER is used everywhere, so its better to override it once
module URI
  remove_const :DEFAULT_PARSER
  unreserved = REGEXP::PATTERN::UNRESERVED
  DEFAULT_PARSER = Parser.new(:UNRESERVED => unreserved + "\{\}\^")
end

GenieacsGui::Application.routes.draw do
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'log_in' => 'sessions#create'

  root 'home#index'
  get 'devices' => 'devices#index'
  get 'devices/:id' => 'devices#show'
  post 'devices/:id' => 'devices#update'
  delete 'devices/:id' => 'devices#destroy'

  get 'faults' => 'faults#index'
  delete 'faults/:id' => 'faults#destroy'
  post 'tasks/:id/retry' => 'faults#retry_task'
  delete 'tasks/:id' => 'faults#destroy_task'

  get 'presets' => 'presets#index'
  get 'presets/new' => 'presets#new'
  get 'presets/:id/edit' => 'presets#edit'
  post 'presets' => 'presets#update'
  delete 'presets/:id' => 'presets#destroy'

  get 'objects' => 'objects#index'
  get 'objects/new' => 'objects#new'
  get 'objects/:id/edit' => 'objects#edit'
  post 'objects' => 'objects#update'
  delete 'objects/:id' => 'objects#destroy'

  get 'provisions' => 'provisions#index'
  get 'provisions/new' => 'provisions#new'
  get 'provisions/:id/edit' => 'provisions#edit'
  post 'provisions' => 'provisions#update'
  delete 'provisions/:id' => 'provisions#destroy'

  get 'virtual_parameters' => 'virtual_parameters#index'
  get 'virtual_parameters/new' => 'virtual_parameters#new'
  get 'virtual_parameters/:id/edit' => 'virtual_parameters#edit'
  post 'virtual_parameters' => 'virtual_parameters#update'
  delete 'virtual_parameters/:id' => 'virtual_parameters#destroy'

  get 'files' => 'files#index'
  get 'files/new' => 'files#new'
  post 'files' => 'files#upload'
  delete 'files/:id' => 'files#destroy', :constraints => { :id => /.*/ }

  get 'ping/:ip' => 'ping#index', :constraints => { :ip => /[0-9\.]+|[0-9a-f:]+/ }

  resources :users do
    resources :user_roles
  end
  resources :roles do
    resources :privileges
  end

  if Rails.configuration.auth_method == :db
    get 'change_password' => 'change_password#index'
    post 'change_password' => 'change_password#update'
  end
end

genieacs-gui/app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles, class_name:   "UserRole",
                        dependent:    :destroy
  has_many :users, through: :user_roles
  has_many :privileges, dependent: :destroy
  validates :name, presence: true,
                    length: { minimum: 1 }
end

genieacs-gui/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  
  def index
    can?(:read, 'roles') do
      off = params.include?(:page) ? (Integer(params[:page]) - 1) * Rails.configuration.page_size : 0
      lim = Rails.configuration.page_size
      @roles = Role.limit(lim).offset(off)
      @total = Role.count
    end
  end
  
  def new
    can?(:create, 'roles') do
      @role = Role.new
    end
  end
  
  def edit
    can?(:update, 'roles') do
      @role = Role.find(params['id'])
      @total = @role.privileges.count
    end
  end
  
  def create
    can?(:create, 'roles') do
      @role = Role.new(role_params)
      if @role.save
        clear_permissions_cache
        redirect_to roles_path
      else
        render 'new'
      end
    end
  end
  
  def update
    can?(:update, 'roles') do
      @role = Role.find(params['id'])
      if @role.update(role_params)
        clear_permissions_cache
        redirect_to roles_path
      else
          render 'edit'
      end
    end
  end
  
  def destroy
    can?(:delete, 'roles') do
      @role = Role.find(params['id'])
      @role.destroy
      clear_permissions_cache
      redirect_to roles_path
    end
  end

  private
    def role_params
      params.require(:role).permit(:name)
    end
end

genieacs-gui/app/views/roles/_form.html.erb
<%= form_for @role do |f| %>
 
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@role.errors.count, "error") %> prohibited
        this role from being saved:
      </h2>
      <ul>
        <% @role.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

genieacs-gui/app/views/roles/edit.html.erb
<%
content_for :title do 'Edit Role ' + @role.name end
%>
<h1>Editing role</h1>

<%= render 'form' %>

<h2>Privileges</h2>

<table class="records">
  <tr>
    <th>Action</th>
    <th>Weight</th>
    <th>Resource</th>
    <th></th>
  </tr>
  <%= render @role.privileges %>
  <tr>
    <td colspan="4"><%= render 'privileges/form' %></td>
  </tr>
</table>

genieacs-gui/app/views/roles/index.html.erb
<%
content_for :title do 'Role List' end
%>
<h1>Listing roles</h1>

<h2>Showing <%= @total %> roles</h2>

<table class="records">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td class="action"><%= link_to 'Edit', edit_role_path(role) if can?(:update, 'roles') %></td>
    <td class="action"><%= link_to 'Destroy', role_path(role), method: :delete, data: { confirm: 'Are you sure?' } if can?(:delete, 'roles') %></td>
  </tr>
<% end %>
</table>

<%= render partial: 'pagination' %>

<br />

<%= link_to 'New role', new_role_path if can?(:create, 'roles') %>

genieacs-gui/app/views/roles/new.html.erb
<%
content_for :title do 'New Role' end
%>
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>